import type { ProductInterface } from '@/@types/ProductInterface'
import { formatUSD } from '@/utils/formatToUSD'

export const products: ProductInterface[] = [
	{
		id: 'e4f5g6h',
		name: 'HP Pavilion 15',
		description: 'A versatile laptop with a sleek design',
		price: formatUSD(749.99),
		isLiked: false,
		type: 'laptop',
		image: '',
		sells: 3,
		onCart: true,
		cart: {
			quantity: 3,
			unitPrice: 749.99,
			amount: 2249.97,
		},
	},
	{
		id: 'q5r6s7t',
		name: 'Sony WH-1000XM4',
		description: 'Wireless noise-canceling headphones with excellent audio quality',
		price: formatUSD(349.99),
		isLiked: true,
		type: 'headphone',
		image: '',
		sells: 9,
		onCart: false,
		cart: {
			quantity: 0,
			unitPrice: 0,
			amount: 0,
		},
	},
	{
		id: 'u8v9w0x',
		name: 'Apple Watch Series 6',
		description: 'Advanced smartwatch with health and fitness tracking features',
		price: formatUSD(399.99),
		isLiked: false,
		type: 'smartwatch',
		image: '',
		sells: 5,
		onCart: true,
		cart: {
			quantity: 1,
			unitPrice: 399.99,
			amount: 399.99,
		},
	},
	{
		id: 'y1z2a3b',
		name: 'Bose Noise Cancelling Headphones 700',
		description: 'Premium noise-canceling headphones with exceptional sound quality',
		price: formatUSD(399.99),
		isLiked: true,
		type: 'headphone',
		image: '',
		sells: 6,
		onCart: false,
		cart: {
			quantity: 0,
			unitPrice: 0,
			amount: 0,
		},
	},
	{
		id: 'c4d5e6f',
		name: 'Google Pixel 6 Pro',
		description: 'Flagship smartphone with advanced camera and performance',
		price: formatUSD(899.99),
		isLiked: false,
		type: 'smartphone',
		image: '',
		sells: 8,
		onCart: true,
		cart: {
			quantity: 1,
			unitPrice: 899.99,
			amount: 899.99,
		},
	},
	{
		id: 'e4f5g6h',
		name: 'HP Pavilion 15',
		description: 'A versatile laptop with a sleek design',
		price: formatUSD(749.99),
		isLiked: false,
		type: 'laptop',
		image: '',
		sells: 3,
		onCart: true,
		cart: {
			quantity: 3,
			unitPrice: 749.99,
			amount: 2249.97,
		},
	},
	{
		id: 'i9j0k1l',
		name: 'Apple MacBook Air',
		description: 'Lightweight and powerful laptop for everyday use',
		price: formatUSD(999.99),
		isLiked: true,
		type: 'laptop',
		image: '',
		sells: 7,
		onCart: false,
		cart: {
			quantity: 0,
			unitPrice: 0,
			amount: 0,
		},
	},
	{
		id: 'm2n3o4p',
		name: 'Samsung Galaxy S21',
		description: 'Flagship smartphone with advanced camera features',
		price: formatUSD(799.99),
		isLiked: false,
		type: 'smartphone',
		image: '',
		sells: 12,
		onCart: true,
		cart: {
			quantity: 1,
			unitPrice: 799.99,
			amount: 799.99,
		},
	},
	{
		id: 'g7h8i9j',
		name: 'Samsung Galaxy Watch 4',
		description: 'Versatile smartwatch with fitness and health tracking features',
		price: formatUSD(249.99),
		isLiked: true,
		type: 'smartwatch',
		image: '',
		sells: 4,
		onCart: false,
		cart: {
			quantity: 0,
			unitPrice: 0,
			amount: 0,
		},
	},
];
