import type { ProductInterface } from '@/@types/ProductInterface'
import { formatUSD } from '@/utils/formatToUSD'

export const products: ProductInterface[] = [
	{
		id: 'u8v9w0x1',
		name: 'MacBook Pro',
		description: '16-inch, 2021, Apple M1 Pro chip',
		price: formatUSD(2499.99),
		isLiked: true,
		type: 'laptop',
		image: '',
		sells: 120,
		onCart: false,
		cart: {
			quantity: 0,
			unitPrice: 0,
			amount: 0,
		},
	},
	{
		id: 'u8v9w0x2',
		name: 'Sony WH-1000XM4',
		description: 'Noise Cancelling Wireless Headphones',
		price: formatUSD(349.99),
		isLiked: false,
		type: 'headphone',
		image: '',
		sells: 200,
		onCart: true,
		cart: {
			quantity: 2,
			unitPrice: 349.99,
			amount: 699.98,
		},
	},
	{
		id: 'u8v9w0x3',
		name: 'iPhone 13 Pro',
		description: '256GB, Graphite',
		price: formatUSD(999.99),
		isLiked: true,
		type: 'smartphone',
		image: '',
		sells: 350,
		onCart: false,
		cart: {
			quantity: 0,
			unitPrice: 0,
			amount: 0,
		},
	},
	{
		id: 'u8v9w0x4',
		name: 'Samsung Galaxy Watch 4',
		description: '44mm, Black',
		price: formatUSD(249.99),
		isLiked: false,
		type: 'smartwatch',
		image: '',
		sells: 180,
		onCart: true,
		cart: {
			quantity: 1,
			unitPrice: 249.99,
			amount: 249.99,
		},
	},
	{
		id: 'u8v9w0x5',
		name: 'Dell XPS 13',
		description: '13.4-inch, 11th Gen Intel Core i7',
		price: formatUSD(1299.99),
		isLiked: true,
		type: 'laptop',
		image: '',
		sells: 90,
		onCart: false,
		cart: {
			quantity: 0,
			unitPrice: 0,
			amount: 0,
		},
	},
	{
		id: 'u8v9w0x6',
		name: 'Bose QuietComfort 35 II',
		description: 'Wireless Bluetooth Headphones, Noise-Cancelling',
		price: formatUSD(299.99),
		isLiked: true,
		type: 'headphone',
		image: '',
		sells: 150,
		onCart: false,
		cart: {
			quantity: 0,
			unitPrice: 0,
			amount: 0,
		},
	},
	{
		id: 'u8v9w0x7',
		name: 'Google Pixel 6',
		description: '128GB, Stormy Black',
		price: formatUSD(599.99),
		isLiked: false,
		type: 'smartphone',
		image: '',
		sells: 250,
		onCart: true,
		cart: {
			quantity: 1,
			unitPrice: 599.99,
			amount: 599.99,
		},
	},
	{
		id: 'u8v9w0x8',
		name: 'Apple Watch Series 7',
		description: '41mm, Blue Aluminum Case',
		price: formatUSD(399.99),
		isLiked: true,
		type: 'smartwatch',
		image: '',
		sells: 220,
		onCart: false,
		cart: {
			quantity: 0,
			unitPrice: 0,
			amount: 0,
		},
	},
	{
		id: 'u8v9w0x9',
		name: 'HP Spectre x360',
		description: '14-inch, Intel Evo, 16GB RAM',
		price: formatUSD(1599.99),
		isLiked: false,
		type: 'laptop',
		image: '',
		sells: 110,
		onCart: true,
		cart: {
			quantity: 1,
			unitPrice: 1599.99,
			amount: 1599.99,
		},
	},
	{
		id: 'u8v9w0x10',
		name: 'JBL Flip 6',
		description: 'Portable Waterproof Bluetooth Speaker',
		price: formatUSD(129.99),
		isLiked: true,
		type: 'headphone',
		image: '',
		sells: 300,
		onCart: false,
		cart: {
			quantity: 0,
			unitPrice: 0,
			amount: 0,
		},
	},
	{
		id: 'u8v9w0x11',
		name: 'OnePlus 9 Pro',
		description: '256GB, Pine Green',
		price: formatUSD(799.99),
		isLiked: false,
		type: 'smartphone',
		image: '',
		sells: 140,
		onCart: true,
		cart: {
			quantity: 1,
			unitPrice: 799.99,
			amount: 799.99,
		},
	},
	{
		id: 'u8v9w0x12',
		name: 'Asus ROG Zephyrus G14',
		description: '14-inch, AMD Ryzen 9, 16GB RAM, RTX 3060',
		price: formatUSD(1599.99),
		isLiked: true,
		type: 'laptop',
		image: '',
		sells: 60,
		onCart: false,
		cart: {
			quantity: 0,
			unitPrice: 0,
			amount: 0,
		},
	},
	{
		id: 'u8v9w0x13',
		name: 'Sony WF-1000XM4',
		description: 'Industry Leading Noise Canceling Truly Wireless Earbuds',
		price: formatUSD(279.99),
		isLiked: false,
		type: 'headphone',
		image: '',
		sells: 170,
		onCart: true,
		cart: {
			quantity: 2,
			unitPrice: 279.99,
			amount: 559.98,
		},
	},
	{
		id: 'u8v9w0x14',
		name: 'Samsung Galaxy S21 Ultra',
		description: '256GB, Phantom Black',
		price: formatUSD(1199.99),
		isLiked: true,
		type: 'smartphone',
		image: '',
		sells: 230,
		onCart: false,
		cart: {
			quantity: 0,
			unitPrice: 0,
			amount: 0,
		},
	},
	{
		id: 'u8v9w0x15',
		name: 'Garmin Fenix 6',
		description: 'Pro Solar, Titanium Carbon Gray DLC with Black Band',
		price: formatUSD(999.99),
		isLiked: false,
		type: 'smartwatch',
		image: '',
		sells: 80,
		onCart: true,
		cart: {
			quantity: 1,
			unitPrice: 999.99,
			amount: 999.99,
		}
	}
];