POST http://localhost:8080/user/signup
content-type: application/json

{
  "name": "teste",
  "email": "teste@gmail.com",
  "password": "12345678"
}

###

POST http://localhost:8080/user/signin 
content-type: application/json

{
  "email": "teste@gmail.com",
  "password": "12345678"
}

###
GET http://localhost:8080/products

###

GET http://localhost:8080/products/clxkhh9ui0001238qy50qeg3k

###

PUT http://localhost:8080/products/liked
content-type: application/json
Authorization: Bearer xxx

{
  "products_ids":["clxkhh9ui0001238qy50qeg3k"]
}

###

GET http://localhost:8080/products/liked/get
content-type: application/json
Authorization: Bearer xxx